webstatDev/idoc_Maison.OLD/idoc/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
#    url(r'^stat/', include('webstat.urls', namespace="webstat")),
    url(r'^', include('webstat.urls', namespace="webstat")),
)

webstatDev/idoc_Maison.OLD/webstat/urls.py
from django.conf.urls import patterns, url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = patterns('',
#    url(r'^home$', 'webstat.views.statview', name='accueil'),
    url(r'^$', 'webstat.views.statview', name='accueil'),
    url(r'^results$', 'webstat.views.result_view', name='results')
)+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

webstatDev/idoc_Maison.OLD/webstat/models.py
#!/usr/bin/env python
#-*-coding:utf-8-*-

__version__ = "0.1"
__license__ = "GPL"
__author__ = "Marc NICOLAS"
__credit__ = "Marc NICOLAS"
__maintainer__ = "Marc NICOLAS"
__email__ = "marc.nicolas@ias.u-psud.fr"
from django.db import models


class webstatModel(models.Model):
    HESIOD = 'HESIOD'
    appChoices = (
        ('HESIOD', 'HESIOD'),
        ('SDO', 'SDO'),
        ('SZCLUSTER', 'SZCLUSTER'),
        ('COROT', 'COROT'),
    )

    application = models.CharField(max_length=55, choices=appChoices, default=HESIOD)

    all_date = models.BooleanField(default=False)
    period_date = models.BooleanField(default=False)

    start_date = models.DateField(blank=True, null=True)
    end_date = models.DateField(blank=True, null=True)

    #is_access_stat = models.BooleanField(default=False)

    is_access_access_by_ip = models.BooleanField(default=False)
    is_access_access_by_months = models.BooleanField(default=False)
    is_access_access_by_country = models.BooleanField(default=False)

#    is_access_vo_by_ip = models.BooleanField(default=False)
#    is_access_vo_by_months = models.BooleanField(default=False)
#    is_access_vo_by_country = models.BooleanField(default=False)

    #is_down_stat = models.BooleanField(default=False)

    is_down_stat_by_user = models.BooleanField(default=False)
    is_down_stat_by_ip = models.BooleanField(default=False)
    is_down_stat_by_country = models.BooleanField(default=False)
    is_down_stat_by_months = models.BooleanField(default=False)
    is_down_stat_by_project = models.BooleanField(default=False)
    is_just_down_stat = models.BooleanField(default=True)

    #nb_element = models.IntegerField()

webstatDev/idoc_Maison.OLD/webstat/forms.py
#-*-coding:utf-8-*-
from django import forms
from models import webstatModel
from datetimewidget.widgets import DateTimeWidget,DateWidget


class webstatForm(forms.ModelForm):

    class Meta:

        model = webstatModel
        fields = ['application', 'all_date', 'period_date', 'start_date', 'end_date',
                  'is_access_access_by_ip', 'is_access_access_by_months', 'is_access_access_by_country',
                  #'is_access_vo_by_ip', 'is_access_vo_by_months', 'is_access_vo_by_country',
                  'is_down_stat_by_user', 'is_down_stat_by_ip', 'is_down_stat_by_country', 'is_down_stat_by_months',
                  'is_down_stat_by_project', 'is_just_down_stat']
                  #, 'nb_element'
        labels = {
            'application': 'Webapp SITools2 ',
            'start_date': 'Du ',
            'end_date': ' Au ',
            'all_date': 'Tous',
            'period_date': 'Sur une période',
            'is_access_access_by_ip': 'Access by Ip',
            'is_access_access_by_months': 'Access by Month',
            'is_access_access_by_country': 'Access by Country',
            #'is_access_vo_by_ip': 'Vo Access by Ip',
            #'is_access_vo_by_months': 'Vo Access by Month',
            #'is_access_vo_by_country': 'Vo Access by Country',
            'is_down_stat_by_user': 'Down by User',
            'is_down_stat_by_ip': 'Down by Ip',
            'is_down_stat_by_country': 'Down by Country',
            'is_down_stat_by_months': 'Down by Month',
            'is_down_stat_by_project': 'Down by Project',
            'is_just_down_stat': 'Just Down',
        }

	dateTimeOptions = {
                'format': 'dd/mm/yyyy',
                #'startView': '',
                'minView': 2,
                'maxView': 2,
                'autoclose': True,
                'clearBtn': 'true',
        }

        widgets = {
            'all_date': forms.CheckboxInput(attrs={"onClick": 'checkIfAll()'}),
            'period_date': forms.CheckboxInput(attrs={"onClick": 'checkIfPeriod()'}),
#            'start_date': DateWidget(usel10n=True, bootstrap_version=3),
#            'end_date': DateWidget(usel10n=True, bootstrap_version=3),
	    #'is_down_stat': forms.CheckboxInput(attrs={"onClick": 'checkIfDownStat()'}),
            #'is_access_stat': forms.CheckboxInput(attrs={"onClick": 'checkIfAccessStat()'}),
            'application': forms.Select(attrs={"onClick": 'onChangeApp()'}),
        }

webstatDev/idoc_Maison.OLD/webstat/views.py
#-*-coding:utf-8-*-

from django.shortcuts import render, get_object_or_404
from webstat.forms import webstatForm
import models
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from webstat.libStatSitools import *

'''
def home(request):
    text = "Welcome on SiTools2 Webstat Interface"
    return render(request, 'home.html', locals())
'''

def statview(request):

    if request.method == 'POST':
        form = webstatForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                form_id = models.webstatModel.objects.filter().order_by('-id')[0].id
                request.session['form_id'] = form_id
            except BaseException, e:
                print "Save FAILED : ", str(e)
                return render(request, '500.html', locals())
            return HttpResponseRedirect(reverse('webstat:results'))
    else:
        form = webstatForm()
    return render(request, 'formWebStat.html', locals())


def result_view(request):

    form_id = request.session.get('form_id')
    form = get_object_or_404(models.webstatModel, pk=form_id)

    if form.start_date is None:
        start_tmp = "2012-03-01 00:00:00"
        form.start_date = datetime(int(start_tmp[0:4]), int(start_tmp[5:7]), int(start_tmp[8:10]),
                                   int(start_tmp[11:13]), int(start_tmp[14:16])).date()
    if form.end_date is None:
        form.end_date = datetime.now().date()

    form_dico = instance_dict(form)
    data = stat_log(form.application, form_dico)
    return render(request, 'webStatResults.html', locals())


def instance_dict(instance, key_format=None):
    "Returns a dictionary containing field names and values for the given instance"
    from django.db.models.fields.related import ForeignKey
    if key_format:
        assert '%s' in key_format, 'key_format must contain a %s'
    key = lambda key: key_format and key_format % key or key

    d = {}
    for field in instance._meta.fields:
        attr = field.name
        value = getattr(instance, attr)
        if value is not None and isinstance(field, ForeignKey):
            value = value._get_pk_val()
        d[key(attr)] = value
    for field in instance._meta.many_to_many:
        d[key(field.name)] = [obj._get_pk_val() for obj in getattr(instance, field.attname).all()]
    return d

webstatDev/idoc_Maison.OLD/templates/formWebStat.html
<head>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'forms.css' %}" />
    <script src="{% static 'jquery.min.js' %}"></script>
    <script src="{% static 'jquery-ui.min.js' %}"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">
    <script type="text/javascript" src="{% static 'forms.js'%}"></script>
    <meta charset="UTF-8">
    <title>SiTools2 IDOC Webstat</title>
</head>
<body onload="checkIfAll();onLoad();">
<div id="header" style="text-align: center; font-size: 27px;font-weight: bold">SiTools2 Webstats</div>
<br><br><br>
<div id="allForm">
<form action="{% url 'webstat:accueil' %}" method="post">
    {% csrf_token %}
    <label id="app_label_id">{{ form.application.label }} : </label> {{ form.application }}<br><br>
    <span style="font-size: large;font-weight:bold;">Fichiers de log à analyser : </span><br>
    {{ form.all_date }}<label>&nbsp;{{ form.all_date.label }}</label><br>
    {{ form.period_date }}<label>&nbsp;{{ form.period_date.label }}</label><br>
    <div id="dateWebstat">
        <span class="date_span"><label>{{ form.start_date.label }} :&nbsp; </label> {{ form.start_date }}</span>
        <span class="date_span"><label>{{ form.end_date.label }} :&nbsp; </label> {{ form.end_date }}</span>
    </div>
    <br>
    <span style="font-size: large;font-weight:bold;">Statistiques à calculer : </span><br>
    <ul>   
        <div id="downStatDiv">
            <li><label>Statistiques de Téléchargement :</label></li>
            <div id="downStatChoice">
                <span class="choice_span"> {{ form.is_just_down_stat }} <label>{{ form.is_just_down_stat.label }}</label></span><br>
                <span class="choice_span"> {{ form.is_down_stat_by_ip }} <label>{{ form.is_down_stat_by_ip.label }}</label></span><br>
                <span class="choice_span"> {{ form.is_down_stat_by_country }} <label>{{ form.is_down_stat_by_country.label }}</label></span><br>
                <span class="choice_span"> {{ form.is_down_stat_by_months }} <label>{{ form.is_down_stat_by_months.label }}</label></span><br>
                <span class="choice_span"> {{ form.is_down_stat_by_project }} <label>{{ form.is_down_stat_by_project.label }}</label></span><br>
		<span class="choice_span"> {{ form.is_down_stat_by_user }} <label>{{ form.is_down_stat_by_user.label }}</label></span>
            </div>
        </div>
	<div id="accessStatDiv">
            <li><label>Statistiques d'Accès :</label></li>
            <div id="accessStatChoice">
                <span class="choice_span"> {{ form.is_access_access_by_ip }} <label>{{ form.is_access_access_by_ip.label }}</label></span><br>
                <span class="choice_span"> {{ form.is_access_access_by_months }} <label>{{ form.is_access_access_by_months.label }}</label></span><br>
                <span class="choice_span"> {{ form.is_access_access_by_country }} <label>{{ form.is_access_access_by_country.label }}</label></span><br>
                <span class="choice_span"> {{ form.is_access_vo_by_ip }} <label>{{ form.is_access_vo_by_ip.label }}</label></span><br>
                <span class="choice_span"> {{ form.is_access_vo_by_months }} <label>{{ form.is_access_vo_by_months.label }}</label></span><br>
                <span class="choice_span"> {{ form.is_access_vo_by_country }} <label>{{ form.is_access_vo_by_country.label }}</label></span><br>
            </div>
        </div>
    </ul>
    <div id="class_errors">
    {% if form.errors  %}
        {% for field in form %}
            {% for error in field.errors %}
                <li> {{ field.label }} : {{ error }} </li>
            {% endfor %}
        {% endfor %}
    {% endif %}
    </div>
    <input type="submit" value="Submit" />
</form>
</div>
<div id="chart">
	<div>
		<img sytle="float:left;" src="{% static 'access_by_month.png'%}"><br>
		<b>Récapitulatif mensuel d'accès entre le 1er janvier 2012 et le 1er janvi 20<b>
	</div>
</div>
<div id="footer">
	<div id="logo_idoc"><div>
</div>
</body>

webstatDev/idoc_Maison.OLD/templates/webStatResults.html
<head>
    {% load staticfiles %}
    {% load per_cent_filters %}
    <link rel="stylesheet" href="{% static 'results.css' %}" />
    <!--<script type="text/javascript" src="{% static 'result.js'%}"></script>-->
    <meta charset="UTF-8">
    <title>Sitools2 Webstat Results</title>
</head>
<body>
<div id="header" style="text-align: center; font-size: 27px;font-weight: bold">Statistic from {{ form.application }} {% if form.period_date  %} between {{ form.start_date }} to {{ form.end_date }} {% endif %}</div>
<h2>Download Statistic</h2>
{% if  data.nb_download  %}<div>Number of download : {{ data.nb_download }}</div>{% endif %}
{% if  data.vol_download  %}<div>Volume of download : {{ data.vol_download }}</div>{% endif %}

{% if data.total_down_per_project_chart %}
    <div><object style="height: 720px;width: 900px;" type="image/svg+xml" data="{{ data.total_down_per_project_chart.0 }}"></object><br>
    <span class="annotation">les données représentant moins de {{ data.dico_cste.dico_max_per_cent.is_down_stat_by_project|per_cent_filters }} % ne sont pas prises en compte.</span><br>
    <a href="{{ data.total_down_per_project_chart.1 }}" download="access_by_ip">download_stat_by_project.png</a></div>
{% endif %}

{% if data.total_down_per_month_chart %}
    <div><object style="height: 720px;width: 900px;" type="image/svg+xml" data="{{ data.total_down_per_month_chart.0 }}"></object><br>
<a href="{{ data.total_down_per_month_chart.1 }}" download="access_by_ip">lien vers le png !!</a></div>
{% endif %}

{% if data.total_down_per_country_chart %}
    <div><object style="height: 720px;width: 900px;" type="image/svg+xml" data="{{ data.total_down_per_country_chart.0 }}"></object><br>
    <span class="annotation">les données représentant moins de {{ data.dico_cste.dico_max_per_cent.is_down_stat_by_country|per_cent_filters }} % ne sont pas prises en compte.</span><br>
    <a href="{{ data.total_down_per_country_chart.1 }}" download="access_by_ip">lien vers le png !!</a></div>
{% endif %}
{% if data.total_down_per_ip_chart %}
    <div><object style="height: 720px;width: 900px;" type="image/svg+xml" data="{{ data.total_down_per_ip_chart.0 }}"></object><br>
    <span class="annotation">les données représentant moins de {{ data.dico_cste.dico_max_per_cent.is_down_stat_by_ip|per_cent_filters }} % ne sont pas prises en compte.</span><br>
    <a href="{{ data.total_down_per_ip_chart.1 }}" download="access_by_ip">lien vers le png !!</a></div>
{% endif %}

<br>
<h2>Access Statistic</h2>
{% if  data.nb_access_ip %}<div id="nbResults">Number of access  : <span class="results">{{ data.nb_access_ip }}</span></div>{% endif %}
{% if  data.nb_vo_ip  %}<div id="nbResults">Number of  VO access  : <span class="results">{{ data.nb_vo_ip }}</span></div>{% endif %}
{% if data.access_ip_chart_svg_png %}
<div><object style="height: 720px;width: 900px;" type="image/svg+xml" data="{{ data.access_ip_chart_svg_png.0 }}"></object><br>
<a href="{{ data.access_ip_chart_svg_png.1 }}" download="access_by_ip">lien vers le png !!</a></div>
{% endif %}

{% if data.access_country_chart_svg_png %}
<div><object style="height: 720px;width: 900px;" type="image/svg+xml" data="{{ data.access_country_chart_svg_png.0 }}"></object><br>
<a href="{{ data.access_country_chart_svg_png.1 }}" download="access_by_country">lien vers le png !!</a>
</div>
{% endif %}

{%  if data.access_month_chart_svg_png  %}
<div><object style="height: 720px;width: 900px;" type="image/svg+xml" data="{{ data.access_month_chart_svg_png.0 }}"></object><br>
<a href="{{ data.access_month_chart_svg_png.1 }}" download="access_by_month">lien vers le png !!</a>
</div>
{% endif %}
<br>
</body>